spring:
  application:
    name: archetype-api-testcontainers
  datasource:
    url: jdbc:postgresql://postgres:5432/ed-db-archetype-testcontainers
    driver-class-name: org.postgresql.Driver
    username: app-user
    password: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
